const fieldsOfLaw = [
    'Administrative Law',
    'Admiralty and Maritime Law',
    'Antitrust and Trade Regulation',
    'Appellate Practice',
    'Aviation and Aerospace',
    'Banking Law',
    'Bankruptcy',
    'Business Law',
    'Civil Rights',
    'Commercial Law',
    'Communications Law',
    'Constitutional Law',
    'Construction Law',
    'Contracts',
    'Corporate Law',
    'Criminal Law',
    'Education Law',
    'Elder Law',
    'Election, Campaign and Political Law',
    'Employee Benefits',
    'Energy Law',
    'Entertainment and Sports Law',
    'Environmental Law',
    'Family Law',
    'Finance',
    'Government Contracts',
    'Health Care Law',
    'Immigration Law',
    'Insurance Law',
    'Intellectual Property',
    'International Law',
    'Labor and Employment',
    'Litigation',
    'Mergers and Acquisitions',
    'Military Law',
    'Natural Resources Law',
    'Personal Injury',
    'Product Liability',
    'Professional Liability',
    'Real Estate',
    'Securities Law',
    'Tax Law',
    'Technology and Science',
    'Torts',
    'Transportation Law',
    'Trusts and Estates',
    'Workers\' Compensation',
    'Zoning, Planning and Land Use'
  ];

  const lawSystems = [
    "Common Law (USA)",
    "Civil Law (France)",
    "Islamic Law (Sharia)",
    "Roman Law (Ancient Rome)",
    "Napoleonic Code (France)",
    "Germanic Law (Germany)",
    "Customary Law (Various Countries)",
    "Talmudic Law (Jewish Law)",
    "Hindu Law (India)",
    "Chinese Legal Tradition (China)",
    "Japanese Legal Tradition (Japan)",
    "Commonwealth Law (UK and Former British Colonies)",
    "Scandinavian Legal Tradition (Nordic Countries)",
    "Soviet Law (Former Soviet Union)",
    "International Law (Global)",
    "Indigenous Legal Systems (Various Indigenous Peoples)",
  ];

  const typesOfSubpoenas = [
    'Subpoena ad testificandum', // For compelling witness testimony in court
    'Subpoena duces tecum', // For requiring documents, materials, or other tangible evidence
    'Deposition Subpoena', // For compelling testimony at a deposition
    'Subpoena to Produce Documents or Permit Inspection', // For producing evidence or allowing property inspection
    'Subpoena for Personal Appearance',
    'Subpoena for Trial', 
    'Subpoena for Hearing', 
    'Subpoena for Arbitration',
    'Information Subpoena',
    'Subpoena for Medical Records', 
    'Subpoena for Employment Records',
    'Subpoena for Bank Records',
    'Subpoena for School Records', 
    'Subpoena for Cellular Records',
    'Subpoena for Internet Records',
    'Subpoena for Expert\'s Testimony' 
];

export {fieldsOfLaw, lawSystems, typesOfSubpoenas}